### ISSUE TITLE
[Feature Request] Dockerfile

### ISSUE THREAD

**Issue by SettingDust** [Dreamacro/clash-dashboard#17]
请求添加Dockerfile，虽然已经有别人写了（

**Comment by Dreamacro** [comment]
这个 UI 没有很明显的版本划分，其实不是很适合作为一个 docker image

**Comment by SettingDust** [comment]
可以和clash整合为一个image

**Comment by Dreamacro** [comment]
整合应该是不可能的，你可以把编译好的版本 gh-page 分支挂载到 clash 的容器里

**Comment by SettingDust** [comment]
不可能是从和说起的？不太理解，貌似目前有一个image是整合的

**Comment by Mosney** [comment]
求发docker版+1
要不然部署起来还是比较...麻烦啊，就算只是个WebUI发个docker也是没问题的，参考AriaNG本身也只是个前端。

**Comment by Dreamacro** [comment]
@Mosney 分开就意味着我需要给 webui 起一个 file server，然而 clash 也会给 `external-ui` 起一个 file server，就会显得很冗余

**Comment by Mosney** [comment]
诶？clash本身有Web UI么？

**Comment by Dreamacro** [comment]
external-ui 设置一个 path, 把静态文件放进去就行，第三方 UI 也可以

**Comment by Mosney** [comment]
清楚了 这样子也挺好

**Comment by Dreamacro** [comment]
@SettingDust 首先两个项目的开发是分开的，要放到一起就得放到 clash 的 image 中，而 clash 的更新进度和 dashboard 的更新进度并不统一，可能会导致某些版本的 image 中存在着有问题的 dashboard，我认为最好的使用方式就是使用 `external-ui` 参数

```yml
version: '3'
services:
  clash:
    image: dreamacro/clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      - ./ui:/ui
    ports:
      - "7890:7890"
      - "7891:7891"
      # If you need external controller, you can export this port.
      # - "8080:8080"
    restart: always
    # When your system is Linux, you can use `network_mode: "host"` directly.
    network_mode: "bridge"
    container_name: clash
```

在 ui 文件夹中放入任意 dashboard 即可，config 里设置 `external-ui: /ui`，岂不是更灵活
